In [1]:
import pandas as pd

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score

In [3]:
a=pd.read_csv("text_classification.csv",names=["message","review"])
a

                                 message review
0                   I love this sandwich    pos
1               this is an amazing place    pos
2     I feel very good about these beers    pos
3                   this is my best work    pos
4                   what an awesome view    pos
5          I do not like this restaurant    neg
6               I am tired of this stuff    neg
7                 I can't deal with this    neg
8                   he is my sworn enemy    neg
9                    my boss is horrible    neg
10              this is an awesome place    pos
11  I donot like the taste of this juice    neg
12                       I love to dance    pos
13     I am sick and tired of this place    neg
14                  what a great holiday    pos
15        that is a bad locality to stay    neg
16        we will have good fun tomorrow    pos
17      I went to my enemy's house today    neg

In [8]:
a["labelnum"]=a["review"].map({'pos':1,'neg':0})
a.head()

                              message review  labelnum
0                I love this sandwich    pos         1
1            this is an amazing place    pos         1
2  I feel very good about these beers    pos         1
3                this is my best work    pos         1
4                what an awesome view    pos         1

In [7]:
x=a["message"]
y=a["labelnum"]
print(x.head(),y.head())

0                  I love this sandwich
1              this is an amazing place
2    I feel very good about these beers
3                  this is my best work
4                  what an awesome view
Name: message, dtype: object 0    1
1    1
2    1
3    1
4    1
Name: labelnum, dtype: int64

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)
print(x_train.shape,x_test.shape)

(14,) (4,)

In [15]:
cv=CountVectorizer()
x_train_trans=cv.fit_transform(x_train)
x_test_trans=cv.transform(x_test)
print(cv.get_feature_names_out())

['am' 'an' 'and' 'awesome' 'bad' 'best' 'boss' 'can' 'dance' 'deal' 'do'
 'enemy' 'fun' 'good' 'have' 'he' 'horrible' 'house' 'is' 'like'
 'locality' 'love' 'my' 'not' 'of' 'place' 'restaurant' 'sandwich' 'sick'
 'stay' 'stuff' 'sworn' 'that' 'this' 'tired' 'to' 'today' 'tomorrow'
 'view' 'we' 'went' 'what' 'will' 'with' 'work']

In [16]:
df=pd.DataFrame(x_train_trans.toarray(),columns=cv.get_feature_names_out())
df

,am,an,and,awesome,bad,best,boss,can,dance,deal,...,to,today,tomorrow,view,we,went,what,will,with,work
0,0,1,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
1,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,1,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
clf=MultinomialNB().fit(x_train_trans,y_train)
pred=clf.predict(x_test_trans)

In [24]:
print("Accuracy:",accuracy_score(y_test,pred))
print("Confusion matrix:",confusion_matrix(y_test,pred))
print("Precision score:",precision_score(y_test,pred))
print("Recall score:",recall_score(y_test,pred))

Accuracy: 1.0
Confusion matrix: [[1 0]
 [0 3]]
Precision score: 1.0
Recall score: 1.0